language: java
env:
  global:
    - # ^^ OSSRH_USERNAME
    - secure: "AFk83C3/ylfg+LR1QsDRFzDYonfRn/12FVYWh6ysNwitgKZTCB4y9euOuZMorH3dYJWQaP4q0gVojdJ0K4jQ37MHrITJr5mfpYahtWADakN9iRz5JK9YkCKrCPy2YDmyPWB0lLfSsxRI+c6xuJXtLf2RRpJiyQV9yiIXgwGsKRVkFrsAlnHzs35nGLT9Lx8RXQ81FzAqC/H8p3TmdlyhRBqZ5QZ7JHSR8cUJUIuyq0Ad6JtSA3mxh6/UBapzO/pH6yawgjX2mxY59lRQZLjP+NWSziOB/3zSPK+/vZxVBzyhEKIZuWKik2S1mLlpkNEzSJd7+aqdMs8sFQaKqdn4Dcd0kud24DKhHHnK2B7TTojAUU9jj0VaJcrI1syfCi+ThZt5P3gxCl5QERALYXc2VLyTFWDEpX6ZCLuAiGHSxn+zp+APjLVmOlqACIrfzoLWHEk3YOWsvIlx+rNX7pQhEbKIA0D7h4ctnjeTnEAZvliwBIKTz43Z2sC5LZqF2PXKDSlETcbJ4mfP6HKCssPQRF/fvBme+0EKlxEZDzVGJnI61kIcnkP8HcKNQEj7gl/Qh5pusontVhwCdLvpMnjx+Lp3hQeXR0+JE03IrMmWEzT+PiPzk9GGFS1cvTur/xxH6aqRaWxIU2z6LDHjvhPfh2u8er0YeThoogRLvrcykaI="
    - # ^^ OSSRH_PASSWORD
    - secure: "xTV29LSKywV/DwpbrhAlBFYrJ0EXnfY/ifyLGSFuRdWwhNxgcdUxTYT5Fn0ceNclEHsiM4vhP/lyIyhbbR2tp6weffupZ6oZaqpl5NAIRkm3MsukeIfih/r9l0tVTuhKxT2zYN9D7BIQBjc7/zp+0n1p0loLPKRRKtOeXpc7ehibgUE5U1OAaraTRFfYTFPcKrGn2HkZiq3t2Z6BOgNaDLv4smhVexO9OvtR1Xcgctl2Joyn798ZHX3DFzuGkMSKiKZHIdDzA4renyKGbEU3BdI2MLVqOe+ojRpsL0fdi7NS5mwUbPrKNNii+FIC8E3HGbmm1MS2EqhNyhZLXwbFomYuoz9SVCGtBrFp9vNB8XXUuWi0JrnljpI9OBYZH6wFfmeKB43JMPh79ziK5dTOMzMx2APQWSZMbD8+rmjpKh/i9JNjjFsRYord1yG5etYnwiN9AC/9CZluqKb9DUlo6q3RRlIA7QMo+M3xrb/UqzkMpTevSn3EUBorYum88mWGHjRaHyIryZt5Ex8qUFDS9FgJBxzx5lVPzgf22jfH03+QRGBDpaWB5HfI34vuD81+9gckh7Jy3rN3SCjJlZN3HrXWGRKEW1VJGluVgJpxG2hCM2r94ldNwt/nWT8EnKtLZ7mVdNWCPiCQJIkbRj6rj8TmSaxIdlv7oh7STOYklm8="
    - # ^^ GPG_KEY_NAME
    - secure: "Joh3F/0VB9HDv1egKgezrdPSDCpRdFwrxgvCqOTkEAxpnSz2/zYO+pwdbt7ui/vc4j+l9iKyFTWcESYNOUUzaiPf9+sHr4N80wgDy//MOxep6qg1JXbsJgHNAPMJj+bm6ZXaY9a5MNxqZiRaUxFPIRUg1uT50gkNbfErFAyh204oD/Ghi8h/OL/0xwdCC/NdmzkFrlODMpJtPJqunjr2XAVW29mSlpKAid3J5SX57g9RFVj/ELo5EBzi4uE8MrQU6VSETpcGjVRR3jlJq6uBdJzZb/5LztBddGYqLrvDNWaoRcAHewBCW3klMnLLbEFFdZdvT/AbAgUenCIEvw4k3gYm4pMLaMqI70P/9l8rPpJl27PCuTVWM4HHhNTEGfr4EzAbUOUAVjGP42FGl9HD/pzNfIsJOQ7vhDUtkCZe0pdQ0fFdGFh1HXiqVN+U066onaoCcuUCjoFAHQgaRIpDEuDJPVbJlSqFS1d1uW9tkBLPcgSwlUivJtfyzm1bc3Z7F4KHnLL6leUXe5ZxqBQyv4mOJ4VSaBGdh/6HSzqYmnbaVb9yHT/OKmMCnnsQazXfjj4LGzB2YDOtQqBarH/ftSvKbJP/zp3YI4GlDs3HlpyxK0ojf9x1x5f4rwN3c2KN5wez0dXvizZGg1G5zSDxTugZ3TRYEaDQYqKqYToQAQI="
    - # ^^ GPG_PASSPHRASE
    - secure: "q3KOdukXDPanqBDWzGbi23E6t6MOgmILfoGCI/Nb2zHpbDqAccOuQFb7/FF0kPvqrIB9oqi7mlYZPV3AteyBqSHWQDchrKsES1ncgatHFlSe2gHrlatroWS1XTnbOXR36Ec8BSlSnLKGSLHdJDfoz2LbDuw8ttLXD/o+W8VhDbRN/mHVAvzRCLnHrPNaPUqIYrTcaFPGka3D6encKrJz+5i9pCYeV3KibWP21D8IgqeSysQvW8AyV1xSDvHCC23BpUIyEbr2qgBjFJ57FTtMTxqxKSKATKEU4W6Scr79bU+9APg2JmNeQwCu6XU+77pHYz100ePqsHmLTVahCq8vFTHEdEhrVgm077Lj9PiZCxeCJg5RzLRiqSST9rwNXz5ZOviIHjSfUfmfgKKwojOwrImcPCWSLvLVgcCRvpD1K0MSgLbIQLqCAu6ZLHnmSUpRpBBejIcTGgTxbXcQRN9DEbiCMtg8sFBveN+Y+PT7cX7mU8p+iHEdceCfin0FNVXZRiuG0OWyN+NJYglG4ZuwY93Bv6pF7hMtMstEDTIqJjJGsWtJHVgdR4NXbH66/3Qk7fnQMqZoCsmtNfBeL6YbwFe/75v8xTFpCn7hfCh4MAz4pPwd8YTfYyz6z+KiIE3qau4VDmVez/3NsyAYr+Fz64lvSJFuxOi/I388ZaI4Jvk="
    - # ^^ GITHUB_TOKEN
    - secure: "pPbmpAOC9ulj/lZeCK44wxaCsffqiAlvY/mYOyA9rhdH6NUmzvs5xwAnhQ4BK/5HBm0kWzmsK5w+O9MkSRhuo2drn6vdGbE/0DRn9i7C3j6moP3Oto7vbXuetiqxZF5T+xrblcZ8qv19OemWeKAkFnCVfnK59mo/rJAtHXecTbn3QqS1D+bLarlybF//62DEawr5HpTlIPkfoYn3wzQUW2PIXh142jcvmczrT7Bgl6nrigfKueClBgcugC35wAYnlyJNcu+BjIZgvFv4BjCuO/cC5eSOYpOlnnC4H/SUIsaNabn+T3kg56LESyCvUTHRdk716Hxu0EhW23HO2zzRkowwHRCS26WMNQ78Ak7Kl/3YBYm4WX1NFSZirb5FehwPSJGqXeYWS5beZ26oFlnw5flWSnMQyc3kgGNbSqkFDs/KtZYoiNhwauQKe4bEA1t1foQ7BSEKaoq28vTD09MDmjnRCe8voEc+Y9WJcM/++qva4NUZv2T5hcC7cAv9Yp1WmxdOWtqiDpwYPREKPKT3NgMkq5ceKPir38XKAiy60ED8+o7Fb5jWguS6KIkrnEtMWX+Z9WB8JKixsNXpzJkb0ZyhIdq6zRxk268+uUKcSzgUmV/aaL8WMrkvfzfuT+Coi750Bkj6FrSqLLEX/kdTd8ciOliQZa2xxju3X5lgboI="
jdk:
  - oraclejdk8
before_install:
  - source ci/setup-git.sh
install: mvn clean install -P !ossrh -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U  --settings ci/mvnsettings.xml
script: mvn verify -P !ossrh -B --settings ci/mvnsettings.xml
after_failure:
  - find . -size +1k -regex  ".*/surefire-reports/.*\.txt" -exec cat {} +
cache:
  directories:
  - "~/.m2/repository"
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  - provider: script
    skip-cleanup: true
    script: bash ci/mvn-release.sh
    on:
      branch: master
  - provider: script
    skip-cleanup: true
    script: bash ci/mvn-deploy.sh
    on:
      branch: develop
  - provider: script
    skip-cleanup: true
    script: bash ci/mvn-deploy.sh
    on:
      tags: true
addons:
  apt:
    packages:
    - libxml2-utils